{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "postgres-operator.selectorLabels" . | nindent 4 }}
{{- end }}
